AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  alexaphoneticalphabet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: phonetic.alphabet.PhoneticAlphabetStreamHandler
      Runtime: java8
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::071436026758:role/lambda_basic_execution'
